Part-I Numpy Questions
Objective:
To build a strong foundation in using NumPy for numerical computations,
including creating arrays, performing operations, and leveraging its
powerful functionalities.

Task 1: Creating Arrays
1. Write a Python program to:
--> Create a 1D NumPy array of 10 integers ranging from 1 to 10.
--> Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
--> Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
2. Display the shape, size, and datatype of each array

In [9]:
import numpy as np
array_1d = np.arange(1, 11)
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Datatype:", array_1d.dtype)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Datatype: int64


In [10]:
import numpy as np
array_2d = np.arange(1, 10).reshape(3, 3)
print("2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Datatype:", array_2d.dtype)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Datatype: int64


In [11]:
import numpy as np
array_3d = np.random.rand(3, 5, 3)
print("3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Datatype:", array_3d.dtype)

3D Array:
[[[0.74158197 0.00167688 0.24968506]
  [0.18291414 0.40413797 0.61604244]
  [0.04539895 0.06217571 0.60825349]
  [0.70542789 0.37689371 0.79053798]
  [0.38007518 0.15199165 0.45374432]]

 [[0.93162509 0.03699525 0.07982708]
  [0.85328625 0.21975589 0.99108854]
  [0.69755568 0.67047727 0.35603326]
  [0.88426334 0.99094392 0.56419039]
  [0.24563711 0.04588708 0.84566212]]

 [[0.87325764 0.00277796 0.38067615]
  [0.35054111 0.67339599 0.27971668]
  [0.94862285 0.29452045 0.59054644]
  [0.3851063  0.72484016 0.69321745]
  [0.54473734 0.9800322  0.29279224]]]
Shape: (3, 5, 3)
Size: 45
Datatype: float64


Task 2: Array Indexing and Slicing:-

1. Create a NumPy array from the following list:
-->data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
2. Write a Python program to:
-->Retrieve the first three elements of the array.
-->Retrieve every alternate element of the array.
-->Reverse the array.
3. Perform the above operations and display the results

In [14]:
import numpy as np
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)
print("Original Array:")
print(arr)

first_three = arr[:3]
print("First three elements:")
print(first_three)

alternate_elements = arr[::2]
print("Every alternate element:")
print(alternate_elements)

reversed_array = arr[::-1]
print("Reversed Array:")
print(reversed_array)


Original Array:
[10 20 30 40 50 60 70 80 90]
First three elements:
[10 20 30]
Every alternate element:
[10 30 50 70 90]
Reversed Array:
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations:-
1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

2. Write a Python program to:-

--> Add, subtract, multiply, and divide the two arrays element-wise.
--> Compute the dot product of the arrays.
--> Find the mean, median, standard deviation, and variance o--> array A.
--> Identify the maximum and minimum values in array B and their indices

In [ ]:
import numpy as np

# 1. Create two arrays A and B with 5 random integers between 1 and 20
A = np.random.randint(1, 21, size=5)
B = np.random.randint(1, 21, size=5)

print("Array A:", A)
print("Array B:", B)
print()

# 2. Element-wise addition, subtraction, multiplication, and division
print("Addition (A + B):", A + B)
print("Subtraction (A - B):", A - B)
print("Multiplication (A * B):", A * B)
print("Division (A / B):", A / B)  
print()


Array A: [ 2 20 14 10 18]
Array B: [17 14 12 10  5]

Addition (A + B): [19 34 26 20 23]
Subtraction (A - B): [-15   6   2   0  13]
Multiplication (A * B): [ 34 280 168 100  90]
Division (A / B): [0.11764706 1.42857143 1.16666667 1.         3.6       ]



In [18]:
# Dot product of A and B
dot_product = np.dot(A, B)
print("Dot Product (A · B):", dot_product)
print()



Dot Product (A · B): 672



In [21]:
# Mean, median, standard deviation, and variance of A
print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Standard Deviation of A:", np.std(A))
print("Variance of A:", np.var(A))
print()



Mean of A: 12.8
Median of A: 14.0
Standard Deviation of A: 6.4
Variance of A: 40.96



In [20]:

# Max, min, and their indices in B
print("Maximum value in B:", np.max(B), "at index", np.argmax(B))
print("Minimum value in B:", np.min(B), "at index", np.argmin(B))

Maximum value in B: 17 at index 0
Minimum value in B: 5 at index 4


Task 4: Reshaping and Transposing
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to:
-->Reshape the array into a 2D array of shape (4, 3).
-->Reshape the array into a 3D array of shape (2, 2, 3).
-->Transpose the reshaped 2D array and display its shape.

In [22]:
import numpy as np

# 1. Create a 1D array of 12 integers from 1 to 12
arr_1d = np.arange(1, 13)
print("Original 1D Array:")
print(arr_1d)
print("Shape:", arr_1d.shape)
print()

# 2. Reshape into a 2D array of shape (4, 3)
arr_2d = arr_1d.reshape(4, 3)
print("Reshaped to 2D Array (4x3):")
print(arr_2d)
print("Shape:", arr_2d.shape)
print()

# 3. Reshape into a 3D array of shape (2, 2, 3)
arr_3d = arr_1d.reshape(2, 2, 3)
print("Reshaped to 3D Array (2x2x3):")
print(arr_3d)
print("Shape:", arr_3d.shape)
print()

# 4. Transpose the 2D array and display its shape
transposed_2d = arr_2d.T
print("Transposed 2D Array:")
print(transposed_2d)
print("Shape after transpose:", transposed_2d.shape)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped to 2D Array (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

Reshaped to 3D Array (2x2x3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)

Transposed 2D Array:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape after transpose: (3, 4)


Task 5: Boolean Masking and Filtering:-

1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to:
-->Find all elements greater than 25.
-->Replace all elements less than 30 with 0.
-->Count the number of elements divisible by 5.

In [23]:
import numpy as np

# 1. Create a NumPy array with 15 random integers between 10 and 50
arr = np.random.randint(10, 51, size=15)
print("Original Array:")
print(arr)
print()

# 2a. Find all elements greater than 25
greater_than_25 = arr[arr > 25]
print("Elements greater than 25:")
print(greater_than_25)
print()

# 2b. Replace all elements less than 30 with 0
modified_arr = arr.copy()
modified_arr[modified_arr < 30] = 0
print("Array after replacing elements less than 30 with 0:")
print(modified_arr)
print()

# 2c. Count elements divisible by 5
count_divisible_by_5 = np.sum(arr % 5 == 0)
print("Number of elements divisible by 5:", count_divisible_by_5)


Original Array:
[20 26 12 25 13 39 27 24 16 30 17 16 24 35 16]

Elements greater than 25:
[26 39 27 30 35]

Array after replacing elements less than 30 with 0:
[ 0  0  0  0  0 39  0  0  0 30  0  0  0 35  0]

Number of elements divisible by 5: 4


Task 6: Working with Built-in Functions:-

1. Use NumPy's built-in functions to:
-->Create an array of 10 equally spaced values between 0 and 1.
-->Create an identity matrix of size 4x4.
-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

In [27]:
import numpy as np

# 1a. Create an array of 10 equally spaced values between 0 and 1
equally_spaced = np.linspace(0, 1, 10)
print("Equally spaced values between 0 and 1:")
print(equally_spaced)
print()

Equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]



In [28]:
# 1b. Create an identity matrix of size 4x4
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:")
print(identity_matrix)
print()

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [30]:
# 1c. Generate a 1D array of 20 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=20)
print("Original Random Array:")
print(random_array)

# Sort the array
sorted_array = np.sort(random_array)
print("Sorted Array:")
print(sorted_array)

# Find the 5 largest elements
largest_5 = sorted_array[-5:]
print("5 Largest Elements:")
print(largest_5)

Original Random Array:
[26  5 94 15 92 67 14 32 77 72 81 65 74 87 13 95 14 52 56 91]
Sorted Array:
[ 5 13 14 14 15 26 32 52 56 65 67 72 74 77 81 87 91 92 94 95]
5 Largest Elements:
[87 91 92 94 95]


Task 7: Generic:-

1. Create a Python program that:
-->Generates two large random arrays of size (100, 100).
-->Performs matrix multiplication on the two arrays.
-->Finds the determinant and inverse of the resulting matrix (if possible).
-->Measures the time taken to complete these operations.

In [32]:
import numpy as np
import time

# 1. Generate two large random arrays of size (100, 100)
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Start timing
start_time = time.time()

# 2. Perform matrix multiplication
C = np.dot(A, B)

# 3. Try to find the determinant and inverse
try:
    determinant = np.linalg.det(C)
    inverse = np.linalg.inv(C)
    print("Determinant of the resulting matrix:", determinant)
    print("Inverse calculated successfully.")
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

# End timing
end_time = time.time()
elapsed_time = end_time - start_time

print("\nTime taken for operations: {:.6f} seconds".format(elapsed_time))


Determinant of the resulting matrix: 1.5063630939044328e+51
Inverse calculated successfully.

Time taken for operations: 0.045839 seconds
